name: Build UDX710 Tools

on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
          corepack enable

      - name: build web
        run: |
          cd web
          pnpm install --lockfile=false --ignore-scripts
          pnpm run build

      - name: build server
        run: |
          cd src
          make

      - name: dopack
        run: |
          mkdir -p output/6677
          cp -r web/dist output/6677/
          cp src/build/ofono-server output/6677/server
          cp tools/start.sh output/6677/start.sh
          cp tools/rj45_bridge_watch.sh output/6677/rj45_bridge_watch.sh
          chmod 755 output/6677/server output/6677/start.sh output/6677/rj45_bridge_watch.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: udx710-tools
          path: output
